"use client";
import React, { useEffect, useMemo, useState } from "react";
import { Header, Footer } from "./components";
import { getConfiguratorOptions } from "./lib/api";
import { AlignCenter, AlignLeft, AlignRight, ArrowLeft, ArrowRight, Check, ChevronDown, Crown, Heart, Image as ImageIcon, Minus, Moon, Music2, RotateCcw, Smile, Sparkles, Star, Upload, WandSparkles, Zap } from "lucide-react";
import "./configurator.css";

const STEPS = ["text", "shapes", "color", "backboard", "hardware"];
const STEP_LABELS = { text: "TEXT", shapes: "SHAPES", color: "COLOUR", backboard: "BACKBOARD", hardware: "HARDWARE" };
const FALLBACK = { options: { colors: [{id:"pink",name:"Pink",hex:"#ff2aa8",price:0},{id:"purple",name:"Purple",hex:"#8d3cff",price:0},{id:"blue",name:"Blue",hex:"#198cff",price:0},{id:"cyan",name:"Cyan",hex:"#12dfe5",price:0},{id:"green",name:"Green",hex:"#63df21",price:0},{id:"yellow",name:"Yellow",hex:"#ffd11a",price:0},{id:"orange",name:"Orange",hex:"#ff8618",price:0},{id:"white",name:"White",hex:"#fff",price:0}], sizes:[{id:"small",name:"Small",price:5600,description:"39.5 × 10 in"},{id:"medium",name:"Medium",price:9100,description:"51.5 × 13 in"},{id:"large",name:"Large",price:11400,description:"63.5 × 15 in"},{id:"xl",name:"Extra Large",price:14800,description:"87.5 × 17 in"}], shapes:[{id:"heart",name:"Heart",price:500},{id:"star",name:"Star",price:500},{id:"moon",name:"Moon",price:500},{id:"lightning",name:"Lightning",price:500},{id:"crown",name:"Crown",price:500},{id:"smile",name:"Smile",price:500}], backboards:[{id:"cut",name:"Cut to Shape",price:0,description:"Precision-cut backing that follows your neon"},{id:"whole",name:"Whole Board / Square",price:1200,description:"A clean rectangular acrylic backing"},{id:"none",name:"No Backing / Minimal",price:0,description:"Minimal hardware for a floating look"}], hardware:[{id:"screws",name:"Wall Screws",price:0,description:"Simple wall-mount hardware"},{id:"wire",name:"Hanging Wire",price:300,description:"For suspended installations"},{id:"dimmer",name:"Standard Dimmer",price:500,description:"Brightness control"},{id:"smart",name:"Smart WiFi / Wireless Remote",price:1000,description:"Smart control and remote"},{id:"indoor",name:"Indoor LED",price:0,description:"For indoor installations"},{id:"outdoor",name:"IP67 Waterproof Outdoor",price:900,description:"For protected outdoor use"}]}, fonts:[{id:"neon-script",name:"Neon Script",class:"font-neon-script"},{id:"classic",name:"Classic",class:""}], presentation:{text_color_selection:true,effect_selection:true,shape_color_mode:"single"}};
const roomBackgrounds=[["Dark Room","/images/hero_living.jpg"],["Living Room","/images/better_together.jpg"],["Gaming Room","/images/astro_with_full_moon.png"],["Bedroom","/images/astro_with_moon.png"],["Cafe","/images/wings_and_drinks.png"],["Office","/images/whats_in_the_box.png"],["Concrete Wall","/images/website_banner_01.png"]];
function shapeIcon(name,size=30){const p={size,strokeWidth:1.7};const n=String(name||"").toLowerCase();if(n.includes("heart"))return <Heart {...p}/>;if(n.includes("star"))return <Star {...p}/>;if(n.includes("moon"))return <Moon {...p}/>;if(n.includes("crown"))return <Crown {...p}/>;if(n.includes("smile"))return <Smile {...p}/>;if(n.includes("light"))return <Zap {...p}/>;if(n.includes("music"))return <Music2 {...p}/>;return <Sparkles {...p}/>;}
function money(value){return `₹${Number(value||0).toLocaleString("en-IN")}`;}
export function ConfiguratorExperience({type="custom_neon"}){
 const isMojo=type==="mojo_mix";const[config,setConfig]=useState(null);const[loading,setLoading]=useState(true);const[step,setStep]=useState(0);const[text,setText]=useState("Good Vibes Only");const[font,setFont]=useState(null);const[align,setAlign]=useState("center");const[size,setSize]=useState(null);const[color,setColor]=useState(null);const[multiColor,setMultiColor]=useState(false);const[shapes,setShapes]=useState([]);const[backboard,setBackboard]=useState(null);const[hardware,setHardware]=useState(null);const[background,setBackground]=useState(roomBackgrounds[0][1]);const[wallFile,setWallFile]=useState(null);
 useEffect(()=>{let alive=true;getConfiguratorOptions(type).then(data=>{if(!alive)return;const next=data?.options?data:FALLBACK;setConfig(next);const o=next.options||{};setFont(next.fonts?.[0]||null);setSize(o.sizes?.[0]||null);setColor(o.colors?.[0]||null);setBackboard(o.backboards?.[0]||null);setHardware(o.hardware?.[0]||null);setLoading(false);}).catch(()=>{if(alive){setConfig(FALLBACK);setFont(FALLBACK.fonts[0]);setSize(FALLBACK.options.sizes[0]);setColor(FALLBACK.options.colors[0]);setBackboard(FALLBACK.options.backboards[0]);setHardware(FALLBACK.options.hardware[0]);setLoading(false);}});return()=>{alive=false};},[type]);
 const options=config?.options||FALLBACK.options,fonts=config?.fonts||FALLBACK.fonts,presentation=config?.presentation||{},currentStep=STEPS[step];
 const valid=useMemo(()=>({text:text.trim().length>0&&text.trim().length<=50&&!!font,shapes:true,color:isMojo||!!color,backboard:!!backboard,hardware:!!hardware}),[text,font,color,backboard,hardware,isMojo]);
 const canContinue=valid[currentStep],complete=STEPS.every(k=>valid[k]);const price=useMemo(()=>{let t=Number(size?.price||0)+Number(backboard?.price||0)+Number(hardware?.price||0);shapes.forEach(s=>t+=Number(s.price||0));return t;},[size,backboard,hardware,shapes]);
 function next(){if(canContinue&&step<STEPS.length-1)setStep(v=>v+1)}function back(){if(step>0)setStep(v=>v-1)}function addShape(s){setShapes(v=>[...v,{...s,uid:`${s.id}-${Date.now()}-${Math.random()}` }])}function removeShape(uid){setShapes(v=>v.filter(s=>s.uid!==uid))}function reset(){setText("Good Vibes Only");setShapes([]);setMultiColor(false);setStep(0);setWallFile(null);setBackground(roomBackgrounds[0][1])}function uploadWall(e){const f=e.target.files?.[0];if(!f)return;if(wallFile)URL.revokeObjectURL(wallFile);const u=URL.createObjectURL(f);setWallFile(u);setBackground(u)}
 const textStyle={textAlign:align,fontFamily:font?.class||"inherit",color:isMojo?"transparent":(color?.hex||"#ff2aa8"),backgroundImage:isMojo?"linear-gradient(90deg,#ffde00,#ff7b00,#ff007b,#c400ff,#00d4ff,#ffde00)":undefined,WebkitBackgroundClip:isMojo?"text":undefined,backgroundSize:isMojo?"200% auto":undefined};
 if(loading)return <><Header/><main className="ns-config-loading">Loading your neon builder…</main><Footer/></>;
 return <><Header/><main className={`ns-configurator ${isMojo?"ns-mojo":""}`}><section className="ns-builder-heading"><div className="ns-container"><div className="ns-breadcrumb">Home <ChevronDown size={13}/> {isMojo?"Mojo Mix":"Custom Neon"}</div><h1>CREATE YOUR <em>{isMojo?"MOJO MIX":"CUSTOM NEON"} SIGN</em></h1><p>Design it. See it. Love it. <Heart size={15}/></p><div className="ns-trust-row"><span><WandSparkles/> Live Real-time Preview</span><span><Heart/> Custom Made Just For You</span><span><Sparkles/> Premium Quality & Safe</span><span><Star/> Made in India</span></div></div></section><section className="ns-container ns-builder-shell"><div className="ns-config-layout"><aside className="ns-panel ns-controls"><div className="ns-stepper">{STEPS.map((s,i)=><button key={s} className={`${step===i?"active":""} ${valid[s]?"done":""}`} onClick={()=>i<=step||STEPS.slice(0,i).every(k=>valid[k])?setStep(i):null}><span className="ns-step-num">{valid[s]?<Check size={13}/>:i+1}</span><span>{STEP_LABELS[s]}</span></button>)}</div><div className="ns-control-body">
 {currentStep==="text"&&<><div className="ns-field"><label>YOUR TEXT <small>{text.length}/50</small></label><textarea value={text} maxLength={50} rows={2} onChange={e=>setText(e.target.value)}/></div><div className="ns-field"><label>FONT STYLE</label><select value={font?.id||""} onChange={e=>setFont(fonts.find(f=>String(f.id)===e.target.value)||fonts[0])}>{fonts.map(f=><option key={f.id||f.name} value={f.id||f.name}>{f.name}</option>)}</select></div><div className="ns-field"><label>ALIGNMENT</label><div className="ns-align"><button className={align==="left"?"selected":""} onClick={()=>setAlign("left")}><AlignLeft/></button><button className={align==="center"?"selected":""} onClick={()=>setAlign("center")}><AlignCenter/></button><button className={align==="right"?"selected":""} onClick={()=>setAlign("right")}><AlignRight/></button></div></div><div className="ns-field"><label>SIZE</label><div className="ns-option-list">{options.sizes?.map(s=><button key={s.id} className={size?.id===s.id?"selected":""} onClick={()=>setSize(s)}><span><b>{s.name}</b><small>{s.description||""}</small></span><strong>{money(s.price)}</strong></button>)}</div></div></>}
 {currentStep==="shapes"&&<><div className="ns-section-title"><div><b>ADD SHAPES</b><small>Add one or more decorative elements</small></div></div><div className="ns-shape-grid">{options.shapes?.map(s=><button key={s.id} onClick={()=>addShape(s)}><span>{shapeIcon(s.name)}</span><small>{s.name}</small></button>)}</div>{shapes.length>0&&<div className="ns-added"><label>YOUR SHAPES</label>{shapes.map(s=><div className="ns-added-row" key={s.uid}><span>{shapeIcon(s.name,20)} {s.name}</span><button onClick={()=>removeShape(s.uid)}><Minus size={13}/></button></div>)}</div>}</>}
 {currentStep==="color"&&(isMojo?<div className="ns-mojo-info"><div className="ns-spectrum-demo"/><h3>MOJO SPECTRUM</h3><p>Your text continuously flows through a vibrant multicolour neon effect. No text colour selection is needed.</p><div className="ns-mojo-check"><Check/> Animated multicolour text</div><div className="ns-mojo-check"><Check/> Smooth colour transition</div></div>:<><div className="ns-field"><label>TEXT COLOR</label><div className="ns-color-grid">{options.colors?.map(c=><button key={c.id||c.name} className={color?.id===c.id||color?.name===c.name?"selected":""} style={{background:c.hex}} onClick={()=>setColor(c)} aria-label={c.name}/>)}</div></div>{presentation.text_color_selection!==false&&<label className="ns-toggle"><input type="checkbox" checked={multiColor} onChange={e=>setMultiColor(e.target.checked)}/><span/> Multicolour text</label>}</>)}
 {currentStep==="backboard"&&<div className="ns-card-list">{options.backboards?.map(o=><button key={o.id} className={backboard?.id===o.id?"selected":""} onClick={()=>setBackboard(o)}><span><b>{o.name}</b><small>{o.description||""}</small></span><strong>{Number(o.price||0)?`+${money(o.price)}`:"FREE"}</strong></button>)}</div>}
 {currentStep==="hardware"&&<div className="ns-card-list">{options.hardware?.map(o=><button key={o.id} className={hardware?.id===o.id?"selected":""} onClick={()=>setHardware(o)}><span><b>{o.name}</b><small>{o.description||""}</small></span><strong>{Number(o.price||0)?`+${money(o.price)}`:"FREE"}</strong></button>)}</div>}
 </div><div className="ns-nav-actions"><button className="ns-secondary" disabled={step===0} onClick={back}><ArrowLeft/> BACK</button>{step<STEPS.length-1?<button className="ns-primary" disabled={!canContinue} onClick={next}>NEXT STEP <ArrowRight/></button>:<button className="ns-primary" disabled={!complete}>ADD TO CART <ArrowRight/></button>}</div><div className="ns-mini-completion">{STEPS.map((s,i)=><span key={s} className={valid[s]?"done":i===step?"current":""}/>)}</div></aside>
 <div className="ns-preview-column"><div className="ns-panel ns-preview"><div className="ns-preview-toolbar"><div className="ns-preview-tabs"><button className="active">PREVIEW</button><button>YOUR WALL</button></div><div className="ns-preview-tools"><button onClick={reset} title="Reset"><RotateCcw size={16}/></button></div></div><div className="ns-canvas" style={{backgroundImage:`url("${background}")`}}><div className="ns-canvas-shade"/><div className={`ns-neon-art ${isMojo?"spectrum":""}`}><div className="ns-neon-text" style={textStyle}>{text||"Your Neon"}</div><div className="ns-art-shapes">{shapes.slice(0,6).map(s=><span key={s.uid} className={isMojo?"spectrum":""} style={!isMojo?{color:color?.hex||"#ff2aa8",filter:`drop-shadow(0 0 8px ${color?.hex||"#ff2aa8"})`}:undefined}>{shapeIcon(s.name,62)}</span>)}</div><div className="ns-neon-base-line"/></div></div><div className="ns-background-picker"><div className="ns-bg-title"><b>CHOOSE A BACKGROUND</b><label><input type="file" accept="image/*" onChange={uploadWall}/><Upload size={14}/> UPLOAD YOUR WALL</label></div><div className="ns-bg-grid">{roomBackgrounds.map(([name,src])=><button key={name} className={background===src?"selected":""} onClick={()=>{if(wallFile){URL.revokeObjectURL(wallFile);setWallFile(null)}setBackground(src)}}><img src={src} alt=""/><span>{name}</span>{background===src&&<i><Check size={11}/></i>}</button>)}</div></div></div><div className="ns-summary ns-panel"><div className="ns-summary-title"><Sparkles/><b>YOUR NEON SIGN SUMMARY</b></div><div className="ns-summary-details"><span>Text <b>{text||"—"}</b></span><span>Font <b>{font?.name||"—"}</b></span><span>Colour <b>{isMojo?"MOJO SPECTRUM":multiColor?"Multicolour":color?.name||"—"}</b></span><span>Size <b>{size?.name||"—"}</b></span><span>Shapes <b>{shapes.length?shapes.length:"None"}</b></span><span>Board <b>{backboard?.name||"—"}</b></span></div><div className="ns-price"><small>ESTIMATED PRICE</small><strong>{money(price)}</strong><span>Inclusive of all taxes</span></div><button className="ns-cart-cta" disabled={!complete} onClick={()=>alert("Configuration ready. WooCommerce cart wiring will use the validated server-side product mapping.")}>ADD TO CART <ArrowRight/></button></div></div></div></section></main><Footer/></>;
}
